#!/usr/bin/env bash

export XDG_CURRENT_DESKTOP=scroll
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=scroll

export GDK_BACKEND="wayland,x11,*"
export QT_QPA_PLATFORM="wayland;xcb"
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND=wayland
# So GTK4 applications work when sending dead keys
export GTK_IM_MODULE=simple

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORMTHEME_QT6=qt6ct
export QT_SCALE_FACTOR_ROUNDING_POLICY=RoundPreferFloor

export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export LIBVA_DRIVER_NAME=nvidia

export ELECTRON_OZONE_PLATFORM_HINT=wayland

export XCURSOR_THEME=Bibata-Modern-Ice
export XCURSOR_SIZE=20

# If you want to use the vulkan renderer instead of the gles2 one (more eatures, experimental, better performance) uncomment this line
#export WLR_RENDERER=vulkan
export WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card2

## Start
scroll
